services:
  # Backend API (FastAPI)
  - name: breakout-scanner-backend
    type: web
    runtime: python
    rootDir: backend
    # plan: starter   # ← uncomment if you want to pin it; otherwise omit and pick in UI
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

  # Frontend (React/Vite static)
  - name: breakout-scanner-frontend
    type: web
    runtime: static
    rootDir: frontend
    # plan: free      # ← optional; can omit
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE
        value: https://breakout-scanner-backend.onrender.com
