# render.yaml — backend (FastAPI) + frontend (Static Site)

services:
  # Backend API (FastAPI)
  - name: breakout-scanner-backend
    type: web
    runtime: python          # (use runtime, not env)
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

  # Frontend (React/Vite static site)
  - name: breakout-scanner-frontend
    type: web
    runtime: static          # <-- this is how you declare a static site
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE
        value: https://breakout-scanner-backend.onrender.com
